// Generated by CoffeeScript 1.12.0
(function() {
  var async, camelCase, capitalize, empty, plainText, ref;

  ref = require("fairmont"), async = ref.async, plainText = ref.plainText, camelCase = ref.camelCase, capitalize = ref.capitalize, empty = ref.empty;

  module.exports = async(function*(description) {
    var b, bucket, bucketExists, buckets, i, len, out, s3;
    s3 = (yield require("../../aws")(description.region)).s3;
    bucketExists = async(function*(name) {
      var e, exists;
      try {
        exists = (yield s3.headBucket({
          Bucket: name
        }));
        return true;
      } catch (error) {
        e = error;
        switch (e.statusCode) {
          case 301:
          case 403:
            return true;
          case 404:
            return false;
          default:
            throw e;
        }
      }
    });
    buckets = description.buckets;
    out = [];
    for (i = 0, len = buckets.length; i < len; i++) {
      b = buckets[i];
      if (!((yield bucketExists(b)))) {
        out.push(b);
      }
    }
    out;
    return {
      buckets: (function() {
        var j, len1, results;
        results = [];
        for (j = 0, len1 = out.length; j < len1; j++) {
          bucket = out[j];
          results.push({
            name: bucket,
            resourceTitle: capitalize(camelCase(plainText(bucket)))
          });
        }
        return results;
      })()
    };
  });

}).call(this);
