// Generated by CoffeeScript 1.12.0
(function() {
  var Asset, Method, Type, coffee, context, define, glob, go, include, isType, map, pathWithUnderscore, ref, ref1, ref2, reject, render, save, tee, type;

  ref = require("fairmont"), go = ref.go, map = ref.map, tee = ref.tee, reject = ref.reject, include = ref.include, Type = ref.Type, isType = ref.isType, Method = ref.Method, glob = ref.glob;

  ref1 = require("panda-9000"), define = ref1.define, context = ref1.context, coffee = ref1.coffee;

  ref2 = Asset = require("../asset"), save = ref2.save, render = ref2.render;

  pathWithUnderscore = require("../utils").pathWithUnderscore;

  type = Type.define(Asset);

  define("survey/coffee", function() {
    var e, source;
    try {
      source = "src";
      return go([
        glob("**/*.coffee", source), reject(pathWithUnderscore), map(context(source)), tee(function(arg) {
          var target;
          target = arg.target;
          return target.extension = ".js";
        }), map(function(context) {
          return include(Type.create(type), context);
        }), tee(save)
      ]);
    } catch (error) {
      e = error;
      console.error(e.stack);
      return process.exit();
    }
  });

  Method.define(render, isType(type), coffee);

}).call(this);
