// Generated by CoffeeScript 1.12.0
(function() {
  var Asset, Method, Type, context, createReadStream, define, formats, glob, go, include, isMatch, isType, map, pathWithUnderscore, ref, ref1, ref2, reject, render, save, tee, type, w;

  createReadStream = require("fs").createReadStream;

  ref = require("fairmont"), go = ref.go, map = ref.map, tee = ref.tee, reject = ref.reject, w = ref.w, include = ref.include, Type = ref.Type, isType = ref.isType, isMatch = ref.isMatch, Method = ref.Method, glob = ref.glob;

  ref1 = require("panda-9000"), define = ref1.define, context = ref1.context;

  ref2 = Asset = require("../asset"), save = ref2.save, render = ref2.render;

  pathWithUnderscore = require("../utils").pathWithUnderscore;

  formats = w(".html .css .js .xml .json .yaml");

  type = Type.define(Asset);

  define("survey/pass-thru", function() {
    var e, source;
    try {
      source = "src";
      return go([
        glob("**/*{" + (formats.join(',')) + "}", source), reject(pathWithUnderscore), map(context(source)), tee(function(arg) {
          var source, target;
          source = arg.source, target = arg.target;
          return target.extension = source.extension;
        }), map(function(context) {
          return include(Type.create(type), context);
        }), tee(save)
      ]);
    } catch (error) {
      e = error;
      console.error(e.stack);
      return process.exit();
    }
  });

  Method.define(render, isType(type), function(arg) {
    var source, target;
    source = arg.source, target = arg.target;
    return target.content = createReadStream(source.path);
  });

}).call(this);
