// Generated by CoffeeScript 1.12.0
(function() {
  var call, join, program, read, ref, run;

  join = require("path").join;

  program = require("commander");

  ref = require("fairmont"), call = ref.call, read = ref.read;

  require("./index");

  run = require("panda-9000").run;

  call(function*() {
    var version;
    version = JSON.parse((yield read(join(__dirname, "..", "package.json")))).version;
    program.version(version);
    program.command('build').description('compile the API, Lambdas, and resources to prepare for publishing.').option('-l, --limit', 'Limit build archive to code within src directory').action(function(options) {
      return run("build", [options.limit]);
    });
    program.command('init').description('Initiallize a Panda Sky project.').action(function() {
      return run("init");
    });
    program.command('publish [env]').description('deploy API, Lambdas to AWS infrastructure').action(function(env) {
      return run("publish", [env]);
    });
    program.command('delete [env]').description('deploy API, Lambdas to AWS infrastructure').action(function(env) {
      return run("delete", [env]);
    });
    return program.parse(process.argv);
  });

}).call(this);
