// Generated by CoffeeScript 1.12.0
(function() {
  var async, define, first, ref, sleep;

  define = require("panda-9000").define;

  ref = require("fairmont"), async = ref.async, first = ref.first, sleep = ref.sleep;

  define("delete", async(function*(env) {
    var config, e, id, stack;
    try {
      config = (yield require("./configuration/compile")(env));
      stack = (yield require("./aws/cloudformation")(env, config));
      console.log("Deleting API");
      id = (yield stack["delete"]());
      console.log("Waiting to Confirm Deletion");
      yield stack.deleteWait(id);
      yield stack.postDelete();
      console.log("Done");
    } catch (error) {
      e = error;
      console.log(e.stack);
    }
    return console.log('\u0007');
  }));

}).call(this);
