// Generated by CoffeeScript 1.12.0
(function() {
  var prompt;

  prompt = require("prompt");

  module.exports = {
    setup: function() {
      prompt.message = "";
      prompt.delimiter = "";
      return prompt.start();
    },
    ask: function(questions) {
      return new Promise(function(resolve, reject) {
        return prompt.get(questions, function(error, answers) {
          var k, ref, ref1;
          if (error != null) {
            return reject(error);
          } else {
            for (k in answers) {
              if ((ref = answers[k]) === "yes" || ref === "Yes" || ref === "YES" || ref === "y" || ref === "Y" || ref === "true" || ref === "True") {
                answers[k] = true;
              }
              if ((ref1 = answers[k]) === "no" || ref1 === "No" || ref1 === "NO" || ref1 === "n" || ref1 === "N" || ref1 === "false" || ref1 === "False") {
                answers[k] = false;
              }
            }
            return resolve(answers);
          }
        });
      });
    }
  };

}).call(this);
