// Generated by CoffeeScript 1.12.0
(function() {
  var async, define, first, ref, sleep;

  define = require("panda-9000").define;

  ref = require("fairmont"), async = ref.async, first = ref.first, sleep = ref.sleep;

  define("publish", async(function*(env) {
    var config, e, id, stack;
    try {
      config = (yield require("./configuration/compile")(env));
      stack = (yield require("./aws/cloudformation")(env, config));
      id = (yield stack.publish());
      if (id) {
        console.log("Waiting for deployment to be ready.");
        yield stack.publishWait(id);
      }
      yield stack.postPublish();
      console.log("Done");
    } catch (error) {
      e = error;
      console.error(e.stack);
    }
    return console.log('\u0007');
  }));

}).call(this);
