// Generated by CoffeeScript 1.12.0
(function() {
  var async, exists, isMatch, mkdir, ref, shell;

  ref = require("fairmont"), async = ref.async, isMatch = ref.isMatch, shell = ref.shell, exists = ref.exists, mkdir = ref.mkdir;

  module.exports = {
    pathWithUnderscore: function(path) {
      return isMatch(/(^|\/)_/, path);
    },
    safe_mkdir: async(function*(path, mode) {
      if ((yield exists(path))) {
        console.log("Warning: " + path + " exists. Skipping.");
        return;
      }
      mode || (mode = "0777");
      return (yield mkdir(mode, path));
    }),
    safe_cp: async(function*(original, target) {
      if ((yield exists(target))) {
        console.log("Warning: " + target + " exists. Skipping.");
        return;
      }
      return (yield shell("cp " + original + " " + target));
    })
  };

}).call(this);
