# This is a templatized verion of a CFo template for Amazon API Gateway with
# Lambda backends as the handlers.  This template forms the core of every
# Panda Sky app deployment, with mixins adding resources to the description.
#===============================================================================

# Specify the API Gateway
API:
  Type: "AWS::ApiGateway::RestApi"
  Properties:
    Name: {{gatewayName}}
    Description: {{description}}

LambdaRole:
  Type: "AWS::IAM::Role"
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - "sts:AssumeRole"
    Policies:
      - PolicyName: {{policyName}}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "arn:aws:logs:*:*:*"
            - Effect: Allow
              Action:
                - "s3:*"
              Resource:
                - "arn:aws:s3:::*"

{{#each resources}}
{{#unless rootResource}}
{{gatewayResourceName}}:
  Type: "AWS::ApiGateway::Resource"
  Properties:
    RestApiId:
      Ref: API
    ParentId:
      {{#isnt parent "/"}}
      Ref: {{parentResourceName}}
      {{else}}
      "Fn::GetAtt": ["API", "RootResourceId"]
      {{/isnt}}
    PathPart: "{{pathPart}}"
{{/unless}}

{{name}}OptionsMethod:
  Type: "AWS::ApiGateway::Method"
  Properties:
    RestApiId:
      Ref: API
    ResourceId:
      {{#unless rootResource}}
      Ref: {{gatewayResourceName}}
      {{else}}
      "Fn::GetAtt": ["API", "RootResourceId"]
      {{/unless}}
    AuthorizationType: NONE
    HttpMethod: OPTIONS
    Integration:
      Type: MOCK
      IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            "method.response.header.Access-Control-Allow-Methods": "'{{methodList}}'"
            "method.response.header.Access-Control-Allow-Origin": "'*'"
      RequestTemplates:
        "application/json": "{statusCode: 200}"
    MethodResponses:
      - StatusCode: 200
        ResponseParameters:
          "method.response.header.Access-Control-Allow-Headers": true
          "method.response.header.Access-Control-Allow-Methods": true
          "method.response.header.Access-Control-Allow-Origin": true

{{#each methods}}
{{gatewayMethodName}}:
  {{#unless ../rootResource}}
  {{#if dependencies}}
  DependsOn:
    {{#each dependencies}}
    - {{this}}
    {{/each}}
  {{/if}}
  {{/unless}}
  Type: "AWS::ApiGateway::Method"
  Properties:
    RestApiId:
      Ref: API
    ResourceId:
      {{#unless ../rootResource}}
      Ref: {{../gatewayResourceName}}
      {{else}}
      "Fn::GetAtt": ["API", "RootResourceId"]
      {{/unless}}
    AuthorizationType: NONE
    HttpMethod: {{method}}
    {{#if requestModel}}
    RequestModels:
      "application/json": {{requestModel}}
    {{/if}}
    {{#if parameters}}
    RequestParameters:
    {{#each parameters}}
    {{#if path}}
      "method.request.path.{{name}}": true
    {{else}}
      "method.request.querystring.{{name}}": true
    {{/if}}
    {{/each}}
    {{/if}}
    Integration:
      Type: AWS
      IntegrationHttpMethod: POST
      {{#unless parameters}}
      PassthroughBehavior: WHEN_NO_TEMPLATES
      {{/unless}}
      Uri:
        "Fn::Join":
          - ""
          -
            - "arn:aws:apigateway:"
            - {"Ref": "AWS::Region"}
            - ":lambda:path/2015-03-31/functions/"
            - {"Fn::GetAtt": [{{lambda.handler.name}}, "Arn"]}
            - "/invocations"
      RequestTemplates:
        "application/json": >
          {
            "url": {
              "path": {
                #foreach($param in $input.params().path.keySet())
                "$param": "$util.escapeJavaScript($input.params().path.get($param))"
                #if($foreach.hasNext),#end
                #end
              },
              "query": {
                #foreach($param in $input.params().querystring.keySet())
                "$param": "$util.escapeJavaScript($input.params().querystring.get($param))"
                #if($foreach.hasNext),#end
                #end
              }
            },
            "method": "$context.httpMethod",
            "headers": {
              #foreach($param in $input.params().header.keySet())
              "$param": "$util.escapeJavaScript($input.params().header.get($param))"
              #if($foreach.hasNext),#end
              #end
            },
            "content" : $input.json('$')
          }



      IntegrationResponses:
      {{#each IntegrationResponses}}
        - StatusCode: {{StatusCode}}
        {{#if SelectionPattern}}
          SelectionPattern: {{SelectionPattern}}
        {{/if}}
          ResponseParameters:
          {{#eachProperty ResponseParameters}}
            {{key}}: "{{value}}"
          {{/eachProperty}}

        {{#if ResponseTemplates}}
          ResponseTemplates:
          {{#eachProperty ResponseTemplates}}
            {{key}}: "{{value}}"
          {{/eachProperty}}
        {{/if}}

      {{/each}}

    MethodResponses:
    {{#each MethodResponses}}
      - StatusCode: {{StatusCode}}
        ResponseParameters:
        {{#eachProperty ResponseParameters}}
          {{key}}: {{value}}
        {{/eachProperty}}
    {{/each}}

{{#with lambda}}
{{handler.name}}:
  Type: "AWS::Lambda::Function"
  Properties:
    Description: "Handler for API {{@root.name}}"
    FunctionName: {{function.name}}

    Handler: "lib/sky.handler"
    Role:
      "Fn::GetAtt" : ["LambdaRole", "Arn"]
    Runtime: {{@root.aws.runtime}}
    Environment:
      Variables:
      {{#eachProperty @root.environmentVariables}}
        {{key}}: {{value}}
      {{/eachProperty}}
  {{#if timeout}}
    Timeout: {{timeout}}
  {{/if}}
    Code:
      S3Bucket: {{handler.bucket}}
      S3Key: "package.zip"

{{permission.name}}:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        "Fn::GetAtt": [{{handler.name}}, "Arn"]
      Principal: apigateway.amazonaws.com
      SourceArn:
        "Fn::Join":
          - ""
          -
            - "arn:aws:execute-api:"
            - {"Ref": "AWS::Region"}
            - ":"
            - {"Ref": "AWS::AccountId"}
            - ":"
            - {"Ref": "API"}
            - {{permission.path}}
{{/with}} # lambda

{{/each}} # action?
{{/each}} # resource?

{{#each schema}}
{{title}}Model:
  Type: "AWS::ApiGateway::Model"
  Properties:
    ContentType: "application/json"
    Description: TBD
    Name: {{title}}
    RestApiId:
      Ref: API
    Schema: '{{json .}}'
{{/each}}

Deployment:
  DependsOn:
  {{#each resources}}
  {{#each methods}}
  - {{gatewayMethodName}}
  {{/each}}
  - {{name}}OptionsMethod
  {{/each}}
  Type: "AWS::ApiGateway::Deployment"
  Properties:
    Description:  {{description}} deployment (generated by Panda Sky)
    RestApiId:
      Ref: API
    StageName: {{@root.env}}
    StageDescription:
      Description: {{@root.env}} for {{description}} (generated by Panda Sky)
      StageName: {{@root.env}}
      MethodSettings:
        - ResourcePath: "/"
          HttpMethod: GET
          MetricsEnabled: true
          DataTraceEnabled: false
          #LoggingLevel: INFO  # OFF, ERROR, INFO
          CachingEnabled: false
          # CacheTtlInSeconds: 1800
          # CacheDataEncrypted: false



# Specify CloudFront Distribution, if required.
{{#if aws.cloudfront}}
CFRDistro:
  DependsOn:
    - Deployment
  Type: "AWS::CloudFront::Distribution"
  Properties:
    DistributionConfig:
      Comment: "Origin is API Gateway deployment {{name}}-{{env}} -
        Setup by Panda Sky."
      Enabled: true
      PriceClass: {{aws.cloudfront.priceClass}}
      DefaultRootObject: ""

      Aliases:
      {{#each aws.cloudfront.aliases}}
        - {{.}}
      {{/each}}

      Origins:
        - Id: {{aws.cloudfront.originID}}
          DomainName:
            "Fn::Join":
              - "."
              -
                - {"Ref": "API"}
                - "execute-api"
                - {"Ref": "AWS::Region"}
                - "amazonaws.com"
          OriginPath: "/{{env}}"
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginProtocolPolicy: "https-only"
            OriginSSLProtocols: [ "SSLv3", "TLSv1" ]

      ViewerCertificate:
        AcmCertificateArn: {{aws.cloudfront.cert}}
        MinimumProtocolVersion: 'TLSv1'
        SslSupportMethod: 'sni-only'


      DefaultCacheBehavior:
        TargetOriginId: {{aws.cloudfront.originID}}
        ForwardedValues:
          QueryString: true
          Cookies:
            Forward: all
          Headers:
            - Accept
            - Authorization
            - "Content-Type"
        DefaultTTL: 0
        MinTTL: 0
        MaxTTL: {{aws.cloudfront.maxTTL}}
        TrustedSigners: []
        ViewerProtocolPolicy: "redirect-to-https"
        AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          - PUT
          - PATCH
          - POST
          - DELETE
        CachedMethods:
          - GET
          - HEAD
          - OPTIONS
        Compress: false
{{/if}}

{{#if aws.route53}}
DNSRecords:
  DependsOn:
    - CFRDistro
  Type: "AWS::Route53::RecordSetGroup"
  Properties:
      Comment: "API Gateway deployment for {{name}}-{{env}} -
        Setup by Panda Sky."
      HostedZoneName: {{aws.route53.domain}}
      RecordSets:
        {{#each aws.route53.hostnames}}
        - Name: {{.}}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2  # CloudFront's HostedZoneId
            DNSName: {"Fn::GetAtt": ["CFRDistro", "DomainName"]}
        {{/each}}
{{/if}}
