// Generated by CoffeeScript 1.12.0
(function() {
  var capitalize, first, ref, toLower, toUpper;

  ref = require("fairmont"), toLower = ref.toLower, capitalize = ref.capitalize, first = ref.first, toUpper = ref.toUpper;

  module.exports = function(description) {
    var a, action, hasDependency, makeCamelName, makeDashName, methods, r, ref1, resource, resources;
    resources = description.resources;
    makeCamelName = function(resource, action) {
      var out;
      out = capitalize(toLower(resource));
      out += capitalize(toLower(action.method));
      return out;
    };
    makeDashName = function(resource, method) {
      var out;
      out = toLower(resource);
      out += "-";
      out += toLower(action.method);
      return out;
    };
    hasDependency = function(signature) {
      if (signature.request || signature.response) {
        return true;
      } else {
        return false;
      }
    };
    for (r in resources) {
      resource = resources[r];
      methods = ["options"];
      ref1 = resource.actions;
      for (a in ref1) {
        action = ref1[a];
        methods.push(action.method);
        resources[r]["actions"][a].camelName = makeCamelName(r, action);
        resources[r]["actions"][a].dashName = makeDashName(r, action);
        resources[r]["actions"][a]["signature"].dependent = hasDependency(action.signature);
      }
      resources[r].methodList = toUpper(methods.join(", "));
    }
    description.resources = resources;
    return description;
  };

}).call(this);
