// Generated by CoffeeScript 1.12.0
(function() {
  var async, empty, randomKey, ref;

  ref = require("fairmont"), async = ref.async, empty = ref.empty;

  randomKey = require("key-forge").randomKey;

  module.exports = async(function*(description) {
    var acm, aws, desired, env, fullyQualify, n, ref1, regularlyQualify;
    env = description.env, aws = description.aws;
    desired = aws.environments[env];
    acm = (yield require("../../../aws/acm")());
    ref1 = require("../../../aws/url")(), regularlyQualify = ref1.regularlyQualify, fullyQualify = ref1.fullyQualify;
    if (!desired.cache || empty(aws.hostnames)) {
      description.aws.cloudfront = false;
      description.aws.route53 = false;
    } else {
      description.aws.cloudfront = {
        originID: "Sky-" + regularlyQualify(aws.hostnames[0]),
        priceClass: "PriceClass_" + (desired.cache.priceClass || "100"),
        aliases: aws.hostnames,
        cert: (yield acm.fetch(aws.hostnames[0])),
        maxTTL: desired.cache.expires || 0
      };
      description.aws.route53 = {
        domain: fullyQualify(aws.domain),
        hostnames: (function() {
          var i, len, ref2, results;
          ref2 = aws.hostnames;
          results = [];
          for (i = 0, len = ref2.length; i < len; i++) {
            n = ref2[i];
            results.push(fullyQualify(n));
          }
          return results;
        })()
      };
    }
    return description;
  });

}).call(this);
