// Generated by CoffeeScript 1.12.0
(function() {
  var async, extractActions, extractCFr, extractParamters, extractResources;

  async = require("fairmont").async;

  extractParamters = require("./parameters");

  extractCFr = require("./cfr");

  extractResources = require("./resources");

  extractActions = require("./actions");

  module.exports = async(function*(description) {
    description = extractParamters(description);
    description = (yield extractCFr(description));
    description = (yield extractResources(description));
    description = (yield extractActions(description));
    return description;
  });

}).call(this);
