// Generated by CoffeeScript 1.12.0
(function() {
  var cat, empty, ref;

  ref = require("fairmont"), cat = ref.cat, empty = ref.empty;

  module.exports = function(description) {
    var extractPath, extractQuery, k, resources, v;
    resources = description.resources;
    extractQuery = function(resource) {
      var i, len, parameter, ref1, results;
      if (resource.query) {
        ref1 = resource.query;
        results = [];
        for (i = 0, len = ref1.length; i < len; i++) {
          parameter = ref1[i];
          results.push({
            name: parameter,
            query: true
          });
        }
        return results;
      } else {
        return [];
      }
    };
    extractPath = function(resource) {
      var i, len, m, parameter, parameters, re, results;
      parameters = [];
      re = /\{([^}]+)\}/g;
      while (m = re.exec(resource.path)) {
        parameters.push(m[1]);
      }
      if (!empty(parameters)) {
        results = [];
        for (i = 0, len = parameters.length; i < len; i++) {
          parameter = parameters[i];
          results.push({
            name: parameter,
            path: true
          });
        }
        return results;
      } else {
        return [];
      }
    };
    for (k in resources) {
      v = resources[k];
      resources[k].parameters = cat(extractQuery(v), extractPath(v));
    }
    description.resources = resources;
    return description;
  };

}).call(this);
