AWSTemplateFormatVersion: "2010-09-09"
Description: Panda Sky Mixin Resources
Parameters:
  LambdaRole:
    Type: String
    Description: ARN of IAM role used by Lambdas.
{{#if vpc}}
  VPC:
    Type: String
    Description: VPC ID for this deployment
  AvailabilityZones:
    Type: String
    Description: comma delimited list of availability zones for the core stack VPC
  SecurityGroups:
    Type: String
    Description: comma delimited list of security groups for the core stack VPC
  Subnets:
    Type: String
    Description: comma delimited list of subnet IDs for the core stack VPC
{{/if}}
Resources:
  {{#each mixins}}
  Mixin{{title}}:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        LambdaRole:
          Ref: LambdaRole
      {{#if @root.vpc}}
        VPC:
          Ref: VPC
        AvailabilityZones:
          Ref: AvailabilityZones
        SecurityGroups:
          Ref: SecurityGroups
        Subnets:
          Ref: Subnets
      {{/if}}
      Tags:
        - Key: Substack Type
          Value: Sky Mixin {{title}}
        {{#each tags}}
        - Key: {{Key}}
          Value: {{Value}}
        {{/each}}
      TemplateURL: "https://{{@root.bucket}}.s3.amazonaws.com/templates/mixins/{{file}}.yaml"
  {{/each}}
