{{#with lambda}}
Handler:
  Type: "AWS::Lambda::Function"
  Properties:
    Description: "Handler for parition {{name}}"
    FunctionName: {{name}}

    Handler: "lib/sky.handler"
    Role: !GetAtt [ IAMRole, Arn ]
    Runtime: {{runtime}}
    MemorySize: {{memorySize}}
    Timeout: {{timeout}}
    {{#if ../vpc}}
    VpcConfig:
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2
    {{/if}}
    Environment:
      Variables:
      {{#each ../variables}}
        {{@key}}: {{this}}
      {{/each}}
    Code:
      S3Bucket: {{code.bucket}}
      S3Key: {{code.key}}
{{/with}}
