require "./commands/build"
require "./commands/delete"
require "./commands/init"
require "./commands/publish"
require "./commands/survey"
require "./commands/survey-custom"
require "./commands/update"
