// Generated by CoffeeScript 1.12.0
(function() {
  var async;

  async = require("fairmont").async;

  module.exports = async(function*(env) {
    var config;
    config = (yield require("./read"));
    config = require("./url")(config, env);
    config = (yield require("./cfo")(config, env));
    return config;
  });

}).call(this);
