// Generated by CoffeeScript 1.12.0
(function() {
  var call, empty, join, read, ref, ref1, resolve, yaml;

  ref = require("path"), join = ref.join, resolve = ref.resolve;

  ref1 = require("fairmont"), call = ref1.call, read = ref1.read, empty = ref1.empty;

  yaml = require("panda-serialize").yaml;

  module.exports = call(function*() {
    var config, e;
    try {
      config = yaml((yield read(resolve(join(process.cwd(), "sky.yaml")))));
    } catch (error) {
      e = error;
      console.error("There was a problem validating this repo's configuration.", e);
      throw new Error();
    }
    return config;
  });

}).call(this);
