// Generated by CoffeeScript 1.12.0
(function() {
  module.exports = function(config, env) {
    var desired, domain, hostnames, i, len, name, ref;
    desired = config.aws.environments[env];
    domain = config.aws.domain;
    hostnames = [];
    ref = desired.hostnames;
    for (i = 0, len = ref.length; i < len; i++) {
      name = ref[i];
      hostnames.push(name + "." + domain);
    }
    if (env.apex === "primary") {
      hostnames.unshift(domain);
    }
    if (desired.apex === "secondary") {
      hostnames.push(domain);
    }
    config.aws.hostnames = hostnames;
    return config;
  };

}).call(this);
